- doc/tensor.md
The documentation related to binary masks for setting or getting tensor values was missing.
> doc: mention ByteTensor for querying/filling elems

- TensorMath.lua
- doc/maths.md
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
Add torch.bmm, which expects two 3D tensors as inputs. A 'b x m x n'
tensor is interpreted as a batch of b matrices of size 'm x n'.
The result is a batch of matrices computed by multiplying the
corresponding pair of matrices in the two input batches.
> Add batch matrix-matrix multiplication.

- Tensor.lua
- init.lua
- test/test.lua
* Currently, you can convert a Storage to a lua table with `storage:totable()`. This patch adds the same functionality to Tensors: `tensor:totable()`. Multidimensional tensors give nested tables of equal shape to the source tensor.
* Add general function for storages and tensors: `torch.totable(...)`.
* Added `torch.isStorage` function.
> torch.totable for Storages and for Tensors.

- TensorMath.lua
- doc/maths.md
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
- behavior is similar to torch.addmm, except that both input
matrices have an additional dimension, as in torch.bmm
- tests cover all use cases
> Add batch matrix-matrix multiplication with accumulation.

- lib/TH/generic/THTensorRandom.c
Previously, getRNGState would return an invalid state if called before any random function call. This would mean that
> require 'torch'
> s = torch.getRNGState()
> =torch.uniform()
0.9989492399618
> torch.setRNGState(s)
> = torch.uniform()
0.046927026240155 -- different result from before, though the state is supposedly the same!!
> Fixed getRNGState in uninitialized case

- TensorMath.lua
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
Just like mm uses addmm, we can write bmm in terms of baddbmm. This way the
two behave the same in terms of when the output is resized.
Also gets rid of unnecessary zeroing out of output of mm and mv.
> Make bmm use baddbmm.

- doc/random.md
- lib/TH/THRandom.c
- lib/TH/generic/THTensorRandom.c
- test/test.lua
The current way the torch RNG is initialized  (THGenerator_new) creates an invalid (unseeded) first RNG state, which is then lazily seeded in a number of functions depending on a valid state. This is error prone (as was seen previously, where getRNGState would potentially return an invalid state). 
I suggest a minor refactor (thanks to @timharley for the suggestion): THGenerator_newUnseeded is provided as a static function in THRandom.c, so that THRandom_manualSeed which does not need a seeded generator can still obtain an unseeded one. On the other hand, THGenerator_new is changed to always return a seeded generator, so that unseeded generators never leak outside of THRandom.c. The lazy seeding is removed from all places where this was previously needed.
Further, THRandom_getState and …
> Make sure RNG is always seeded

- lib/TH/THRandom.c
- lib/TH/THRandom.h
- lib/TH/generic/THTensorRandom.c
After my last PR, the RNG state returned by getRNGState is guaranteed to be valid. RNG states stored previously (with older version of torch) however could be invalid. For this and other reasons, it seems reasonable to check for the edge case of an invalid RNG state in setRNGState and throw an error when invalid. (this seems safer then silently re-seeding such state, leading to non-deterministic behaviour)
I renamed `initf` to `seeded` (as suggested by @timharley) and extracted the validity check into a new function, THRandom_isValidState.
> Checking for valid RNG state

- doc/tensor.md
- generic/Tensor.c
- test/test.lua
This PR exposes the above C functions as Tensor methods. Useful when you want to avoid reallocating memory, which isn't possible with the current `Tensor[mask]` schemes (`maskedSelect` in particular). The PR includes unit tests and doc.
> maskedCopy,maskedFill,maskedSelect

- File.lua
- test/test.lua
These match the previous [de]serialize functions, but return
a torch.CharStorage instead of a Lua string. This can be used to
prevent hitting the LuaJIT 2GB limit for very large objects, because the
CharStorage is allocated on the C side (not counting towards this limit)
but the Lua string will count towards this limit.
This modification fixed a repeatable OOM crash I found for trying to
serialize certain large models.
> Added torch.[de]serialize{To/From}Storage to File.lua.

- lib/TH/generic/THTensorLapack.c
- test/test.lua
The torch.gels function threw a lapack error when calling it with an underdetermined system, i.e., the case m < n. As discussed with @koraykv, I have fixed this and added tests.
> Fixing torch.gels in the underdetermined case.

- lib/luaT/luaT.c
Previously, the existence of the parent class wasn't actually verified, since the return value of luaT_pushmetatable wasn't checked. 
This for instance allowed the following:
my = {}
MyC, p = torch.class('my.class', 'nonexistent.class')
MyC:__init() print('constructor') end
Weird effect:
x = my.class() -- constructor not actually called here! (broken metatable?)
> Fix parent class validity check

- generic/Tensor.c
This pushudata call seems wrong in the case where the result `tensor` is one of the arguments to maskedSelect.
> Remove wrong pushudata

- doc/tensor.md
* Fix link to LuaJIT external API (`http://` had been forgotten, having the link
seen as relative)
* Change `t:noncontinguous:contiguous()` into `t_noncontiguous:contiguous()`
* Change `t_contiguous` into `t_transposed_and_contiguous` (t_contiguous was not defined)
> Fix broken link and typo in doc/tensor

- Tester.lua
The case of empty tensors was handled wrongly: leading to exception. In the test of torch.maskedSelect and similar the case of an empty tensor can occur, leading to occasional test failures.
> fix assertTensorEq for case of empty tensors

- doc/maths.md
- doc/tensor.md
All these changes are superficial typograhic changes, but they
try and unify a bit its consistency.
I had to make some choices among the different usages I found:
* Display all tensor sizes with the syntax `m x n`
(found mxn, m-by-n)
* Add `` arround isolated variables and everything that is code
* Specify that code blacks are in Lua using the GitHub ```lua syntax
* Put commas inside brackets when arguments are optional
e.g. commas for [resval, resind,] x [,d] [,flag]
or also [res,] x, k [, 'F' or 'V']
* Use '> ' as prompt and display it only if the returned value is then
shown (and so don't use = or print)
(found '>', '=', '= ', '> = ', 't7> ', etc. )
Still work to do on it.
* Add spaces around * or = but not after commas (this is the guideline
used in the majority of cases), except in …
```
> Improve consistency of documentation typography

- Tester.lua
This change allows to use assertTensorEq to check for exact equality (previously setting precision = 0 would have made the condition unsatisfiable)
> Improve assertTensorEq to work with precision 0

- Tensor.lua
They where displayed with narrower columns than others.
For instance, before this commit:
```lua
> torch.Tensor(2,2):zero()
0 0
0 0
[torch.DoubleTensor of dimension 2x2]
> torch.Tensor(2,2):fill(1)
1  1
1  1
[torch.DoubleTensor of dimension 2x2]
```
This is because `log10()` is used to determine number width in base 10
but the case where it is 0 is handled differently.
> Change display of null tensors

- doc/tensor.md
As it seems to be ok, I continue what I started in #177 while reading the doc.
Here is an update of `tensor.md` esepcially focused on code blocks.
* Use '> ' as prompt when the returned value is displayed
* Use no prompt when there is no returned value
* Do not use print or return to display a value (it introduces extra parenthesis and noisy characters)
* Skip a line after displayed value, but not before
* (In tensor.md only)
> Homogenize style of code blocks

- lib/TH/cmake/FindSSE.cmake
This commit adds initial values to test programs in FindSSE.cmake.
Without these, the vc2013 debug runtime will complain "The variable 'b' is being used without being initialized." when the test program is run, and then mark SSE4* as unsupported.
> Fix FindSSE SSE4* check crash on MSVC.

- doc/tensor.md
Changed the way random mask tensors are created in examples, by using torch.ByteTensor(...):bernoulli() instead of torch.DoubleTensor(..):rand():mul(2):floor():resize(...)
> Minor documentation changes

- doc/random.md
- lib/TH/THRandom.c
- lib/TH/THRandom.h
- lib/TH/generic/THTensorRandom.c
Cleaned up some bits of RNG code:
* removed obsolete declarations of no longer existent functions  THRandom_getState/setState
* replaced THRandom_isValidState by THGenerator_isValid
* changed \_\_uniform\_\_ to use THRandom_random (code was practically identical) , which removes a brittleness in how the nextState has to be generated (tricky, error-prone 3 lines of code which were reused in two places previously)
> Minor refactoring of RNG code

- TensorMath.lua
- doc/maths.md
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
Added kthvalue function, to select k-th smallest value. Interface as close as possible to min/max, i.e. returns values and indices. Based on Quickselect algorithm (i.e. linear time) adapted from [this](http://ndevilla.free.fr/median/median/src/quickselect.c) Public Domain implementation, somewhat changed with tricks from the Quicksort implementation used in Torch.
Also added median function based on same algorithm. Median returns 'middle' element in case of odd-many elements, otherwise one-before-middle element (could also do the other convention to take mean of the two around-the-middle elements, but that would be twice more expensive, so I decided for this one).
> Added kthvalue and median operations, tests, doc

- lib/TH/THMemoryFile.c
DiskFile was fixed [here](https://github.com/torch/torch7/pull/32), but not MemoryFile.
> Fixed serialization in ASCII, for MemoryFile.

- doc/maths.md
This is a very minor correction for the documentation. There is a typo in torch.range section. `step` is misspelled as `setp`.
> A typo, 'setp', is corrected to 'step'

- Tensor.lua
The string that `Tensor.__tostring__` function returns includes size of different dimensions of the tensor (`tensor:size()`), but not the dimension of the tensor (`tensor:dim()`). For example, the dimension of the `torch.rand(7)`, which is obtained by `torch.rand(7):dim()` is 1, whereas `Tensor.__tostring__` returns
`[torch.DoubleTensor of dimension 7]`,
which is incorrect. This is a tensor of dimension 1, size 7. The same problem exists for Tensors of dimension 2 and beyond. For instance, for `torch.rand(8,5)` the `Tensor.__tostring__` function returns
`[torch.DoubleTensor of dimension 8x5]`
instead of returning `[torch.DoubleTensor of dimension 2]` as expected by `torch.rand(8,5):dim()`.
To fix this issue and make the returned description consistent with the terminology of the Torch …
> Fixed inconsistency in Tensor.__tostring__

- lib/TH/generic/THTensor.c
Some of the argument numbers passed to THArgCheck seemed to be off by one, creating confusing error messages. Also, dimension argument wasn't checked to be >= 0, e.g. in THTensor_(squeeze1d) a negative dimension could actually be used leading to segfault.
[ my editor automatically removed trailing whitespace - sorry for the noise ]
> Fix argument checks

- Tensor.lua
- test/test.lua
There was a small bug in `split` when the `result` table was given as input to be reused, as explained in the documentation. Instead of putting the output in `result`, it was only emptying it. It passed the tests because the size of `results` was 0, so it didn't check the assertions.
Added a few more test cases to compare both outputs.
Additionally, I set the `precision` variable to be local in `test.lua`
> Fix bug in split while reusing the result table.

- lib/TH/generic/THTensorMath.c
```lua
a = torch.zeros(2^31-10)
b  = torch.zeros(500)
c= torch.cat(a,b)
```
fails on master, passes now.
Can not add it as a default test case as it is too intensive.
> fixing torch.cat for sizes greater than 2^31

- CMakeLists.txt
- Tensor.lua
- generic/Tensor.c
- generic/TensorOperator.c
- lib/TH/THGeneral.c
- lib/TH/THGeneral.h.in
- lib/TH/THTensor.h
- lib/TH/generic/THTensor.c
- lib/TH/generic/THTensor.h
- lib/TH/generic/THTensorMath.c
* Add C file/line to THError and THArgCheck. Add tensor sizeStr() method.
* Add THAssert THAssertMsg functions.
* Add sizeDesc() and desc() functions, which return tensor descriptor
strings for use in error messages. To avoid memory leaks, we have to pass these
strings on the stack within structs, so it's a bit unwieldly.
* Improved a bunch of error messages.
e.g.
```
th> torch.mm(torch.Tensor(4,4), torch.Tensor(5,5))
size mismatch, m1: [4 x 4], m2: [5 x 5] at /home/alerer/git/torch7-2/lib/TH/generic/THTensorMath.c:511
stack traceback:
...
th> torch.Tensor(1):size(4)
[...]:1: bad argument #1 to 'size' (dimension 4 out of range of 1D tensor at /home/alerer/git/torch7-2/generic/Tensor.c:16)
stack traceback:
...
```
> Add C file/line to THError et al. Add THAssert. Improve error messages.

- lib/TH/THGeneral.c
- lib/TH/generic/THTensorMath.c
This contains two commits to speed up LookupTable operations:
1) Speed up Tensor:index (indexSelect) for contiguous tensors. This speeds up the forward pass of LookupTable by ~90x for large (e.g. 20K) inputs and by 3x for small (e.g. 10) inputs.
2) Align allocated memory on 64 byte boundaries (i.e. cache lines) for allocations larger than 5KB. This speeds up the backwards pass of LookupTable by up to 30% for some sizes and has no effect on others. (It helps when the # of dimensions is a multiple of 64) We only do this for large enough allocations to avoid wasting space.
> Speed up Tensor:index

- lib/TH/generic/THTensorMath.c
Gives another 2-3x over memcpy for large index vectors.
> Use assignment in indexSelect for 1-dimensional contiguous input.

- lib/TH/THGeneral.c
The usage of posix_memalign causes us problems with tcmalloc. I am adding a flag to disable its usage.
> Allowing usage of posix_memalign to be disabled through a new flag, DISABLE_POSIX_MEMALIGN

- lib/TH/cmake/FindBLAS.cmake
- test/test.lua
This is to make sure BLAS F2C auto detection does not fail because of compiler warnings:
error: implicit declaration of function 'exit'
I discovered this problem while re-installing Torch on Mac OS X (10.10.3) with [GCC 5](https://github.com/Homebrew/homebrew-versions/blob/316dddf599f0c34a224374ef1ee6267cea6d1364/gcc5.rb). The dot product between two `float` tensors returned 0.
Looking at cmake outputs I got:
-- Performing Test BLAS_F2C_DOUBLE_WORKS
-- Performing Test BLAS_F2C_DOUBLE_WORKS - Failed
-- Performing Test BLAS_F2C_FLOAT_WORKS
-- Performing Test BLAS_F2C_FLOAT_WORKS - Failed
And CMakeError.log indicated that these auto detection programs failed because of `some warnings being treated as errors`.
I extended the unit test to make sure there is coverage for `sdot`. This extended …
> FindBLAS.cmake: fix missing stdlib.h include

- TensorMath.lua
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
Otherwise it can produce mildly surprising behaviour, in the floating-point setting, due to rounding errors.
For example, we get:
> torch.FloatTensor():range(0.6, 0.9, 0.1)
0.6000
0.7000
0.8000
[torch.FloatTensor of size 3]
When we'd expect:
> torch.range(0.6, 0.9, 0.1)
0.6000
0.7000
0.8000
0.9000
[torch.FloatTensor of size 4]
This happens because the size for the result tensor is computed as 
size = (long)((xmax-xmin)/step+1);
and in single-precision this gives 3. We can avoid this by
* changing the input types to accreal, so that the size is computed at double precision even for FloatTensors.
* dividing by step before subtracting xmin from xmax, which seems to be more robust to rounding error.
Both appear to be necessary in my tests...
> Tweak torch.range to be more numerically robust.

- doc/maths.md
point out htat the dimension-wise operations can also be used matrixwide
I sense from the various '.dok' postfixes that this is generated documentation?  So, this might not be the appropriate place to make this change?
> point out htat the dimension-wise operations can also be used matrixwide

- FFI.lua
The 'default' tensor map (in generic/Tensor.c) makes sure that the
input tensors are of the same type. The FFI implementation (for the
contiguous case) doesn't do that. It should do so for consistency and also
to avoid segfaults when passing in a CudaTensor, for example.
> Make FFI tensor map more robust.

- lib/TH/generic/THTensorMath.c
Prevents segfault when the src tensor is empty.
> Fix loop logic error in maskedCopy.

- test/test.lua
Previously, the tests would pass due to a different error than the one
being tested for.
> Fix tests for scatter and scatterFill.

- TensorMath.lua
Current implementation casts random number to int :-(. @andresy was this intended?
> fixing torch.random(a,b) for a,b >= 2^31

- TensorMath.lua
lua_isstring returns true for a lua_Number. Then lua_tostring was called which led to a re-formatting (#281) that generated a loss of precision for doubles who need more than 14 digits of precision.
Also avoids two useless conversions.  
Replaced by the exclusive (lua_type(L, narg) == LUA_TSTRING) check.
> Change lua_isstring check in torch_random

- CMakeLists.txt
- lib/TH/generic/THTensorConv.c
- lib/TH/generic/THTensorLapack.c
- lib/TH/generic/THTensorRandom.c
Some corrections that allow for compilation in MSVC:
- do not set -Werror compilation flag that MSVC does not understand
- remove TH_API from function definitions for static library compilation
> MSVC corrections

- CMakeLists.txt
- Timer.c
- general.h
- lib/TH/THGeneral.c
- lib/TH/THGeneral.h.in
- lib/luaT/luaT.h
This patch enables Torch7 compilation on Windows using mingw32 (or tdm-gcc with msys/msys2).
The steps needed:
1. Install `torch/cwrap` and `torch/paths`
2. Run the following commands:
```
cmake -E make_directory build
cd build
cmake .. -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DLUALIB=lua51.dll -DLUA_INCDIR="%LUA_INCDIR%" -DLUA_LIBDIR="%LUA_LIBDIR%" -DLUA="%LUA%"
make
```
Related ticket: #150. I've tested this under Windows 8.1 using msys2 and tdm-gcc-4.8, but it should work with other versions and configurations of mingw.
> Add support for compilation on Windows using mingw32

- lib/TH/THGeneral.c
Sam Gross in
9ad68c82f6d5a11db05ec667cbd78d8909c120d2
used _aligned_malloc 
but _aligned_malloc in Win32 requires _alinged_free in all other places (and in those places we do not know if we allocated with malloc - or with _aligned_malloc) - and resulted in crashes in garbage collector
> do not use _aligned_malloc in WIN32: it requires _aligned_[free|realloc]

- lib/TH/generic/THTensorLapack.c
There were some needed argchecks to be done before sending the matrix into lapackClone* functions. The side-effect of not having these argchecks is that if you sent in a 1-D matrix, then the size of the 2nd dimension would be read from uninitialized memory and would not only be garbage, but sometimes you go out-of-memory because of this.
> adding argchecks for Lapack before calls to lapackClone

- init.lua
This supports tensor types that are implemented using cdata.
These cdata objects do not have a unique metatable, but their
names are available through torch.typename.
For Tensors and Storages, we do not need the recursive behavior of torch.isTypeOf.
> Use torch.typename in isTensor and isStorage

- lib/TH/generic/THTensorMath.c
- test/test.lua
- Solves https://github.com/torch/torch7/issues/58
- Also solves the issue of gemm when the resulting tensor has zero stride (as in https://github.com/torch/torch7/issues/289)
- Adds unit test for `torch.mm`, which was missing
> Fix for gemm with zero strides plus add unit test for torch.mm

- init.c
- lib/TH/THGeneral.c
- lib/TH/THGeneral.h.in
The Lua garbage collector isn't aware of torch-allocated memory, so it doesn't know when to run the GC and the user ends up having to call collectgarbage() manually from their script, or running out of memory.
This PR lets THAlloc and THRealloc attempt lua GC if malloc/realloc fails.
This idea is thanks to @colesbury, I just had some free time to implement it.
To demonstrate, you can run the following
```lua
require 'torch'
for i=1,1000 do
print(i)
a = torch.FloatTensor(1000000000):zero()
end
```
This loop will run out of memory prior to this PR, but now the GC will be run.
I'll add this to cutorch as will if this gets acepted.
@soumith @andresy
> THAlloc/THRealloc attempt lua GC on failure

- lib/TH/generic/THTensorMath.c
- test/test.lua
Now min and max always return NaN when the input contains a NaN.
They only returned NaN before when the first element of the input was NaN and the min or max value excluding NaNs otherwise.
> Fix problem with NaNs in max and min

- lib/TH/CMakeLists.txt
- lib/TH/cmake/FindSSE.cmake
- lib/TH/generic/simd/common_simd.h
- lib/TH/generic/simd/convolve.c
- lib/TH/generic/simd/convolve.h
- lib/TH/generic/simd/convolve5x5_avx.c
- lib/TH/generic/simd/convolve5x5_sse.c
This is a pretty specific optimization to Twitter's usage of 5x5 but it could be extended to support more sizes in the future.
> SSE optimizations for 5x5 convolution.

- lib/TH/THGeneral.h.in
- lib/TH/generic/THTensorConv.c
- lib/TH/generic/simd/convolve.c
- utils.h
CMake defines _WIN32.
Implement cpuid and xgetbv with intrin.h
> Making things work under windows

- Tester.lua
It's good for tests to run in a deterministic, sensible order (alphabetical).
Also, it's nice to be able to exit the tester through Ctrl-C when the tests are slow/hang/fail. If anyone has a better way to do that then my error string grepping, please suggest it.
> torch Tester: run tests in alphabetical order, and support interrupt handler

- doc/file.md
This section is describing ``writing'' methods instead of ``reading''.
> document misspelling

- doc/maths.md
- test/test.lua
Added some tests for the previously failing cases of wrong transpositions for in-place LAPACK functions. Added comments to the documentation regarding the fact that return values have non-standard strides.
[ My editor clearly dislikes trailing whitespace, sorry for the noise ]
> Tests and documentation for transpositions in LAPACK functions

- File.lua
When you theoretically write more than 268 million objects using `f:writeObject` on a single file, or `torch.save` a table (or tds.hash) with that many objects, the serialization fails right now due to LuaJIT 2GB limitations.
This is because of the duplicate object tracking we have in place right now in the serializer.
We already have a mode for file objects to disable this duplicate tracking, via:
```lua
f:referenced(false)
```
However, it was still tracking some pointers that are not actually used.
This PR fixes it.
> Serialization at scale, fixes.

- lib/TH/cmake/FindSSE.cmake
This was a bug introduced in #241 from @zakattacktwitter . 
It was tracked down and reported by one of our community users "Alex" in the google groups.
The AVX check was disabled with if (0), so people without AVX support were still having TH attempt to compile the AVX code, and was later failing at the assembler level.
Let me know if I missed anything.
> fixing avx checks

- init.c
- lib/TH/THAtomic.c
- lib/TH/THAtomic.h
- lib/TH/THGeneral.c
- test/test.lua
- utils.c
With torch/threads, Tensors can be allocated in one thread and deallocated in another, so `heapSize` must not be thread-local. Note that I am leaving `heapSoftMax` as thread-local, so each thread will maintain it's own softmax.
Here's an example that this PR fixes:
```lua
```require 'torch'
local Threads = require 'threads'
Threads.serialization('threads.sharedserialize')
local a = torch.Tensor(1e7):zero()
pool = Threads(1, function() require 'torch'; end);
pool:addjob(function() for i = 1,1000 do a:add(1); end; a = nil;  collectgarbage(); end)
a = nil
collectgarbage()
pool:synchronize()
```
If you add an assert that `heapSize >= 0` prior to this PR, it will fail (in the pool thread).
> Fix lua GC to support allocations across multiple threads

- TensorMath.lua
- doc/tensor.md
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
New branch continuing PR #183.
Changes:
- Renamed from `find` to `nonezero`
- Stripped out `ind2sub` and `sub2ind` functions
Finds and returns a `LongTensor` corresponding to the *subcript* indices of all
non-zero elements in `tensor`.
```lua
> x = torch.rand(4, 4):mul(3):floor():int()
> x
2  0  2  0
0  0  1  2
0  2  2  1
2  1  2  2
[torch.IntTensor of dimension 4x4]
> torch.nonzero(x)
1  1
1  3
2  3
2  4
3  2
3  3
3  4
4  1
4  2
4  3
4  4
[torch.LongTensor of dimension 11x2]
> x:nonzero()
1  1
1  3
2  3
2  4
3  2
3  3
3  4
4  1
4  2
4  3
4  4
[torch.LongTensor of dimension 11x2]
> x:eq(1):nonzero()
2  3
3  4
4  2
[torch.LongTensor of dimension 11x2]
```
> Nonzero function for finding non-zero elements of a tensor

- init.lua
Fix the following cases (they raise error now):
torch.isTypeOf("string", "nn.Module")
require 'nn';
m = nn.Module()
m.name = "module"
nn.utils.recursiveType(m, "torch.FloatTensor")
> Fix torch.isTypeOf(<string>, ...)

- doc/random.md
Minor clarification to the doc in that the result of `torch.random` is always unsigned.
> Clarify that `torch.random` result is unsigned

- TensorMath.lua
- doc/maths.md
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
- torchcwrap.lua
Adds a version of torch.cat that takes an array of tensors as inputs.
Adds TensorArray type to cwrap that reads an array of tensors from Lua
and creates a C array of tensor pointers that are passed to the C
function.
> More flexible torch.cat

- README.md
Making the comment about Gitter Chat more prominent. The main reason for me is that, this way, we can automatically remove this section in our internal documentation.
> Added a 'Need help?' section header to the comment about Gitter Chat

- doc/maths.md
The doc is confusing - currently TensorOperator only supports 1Dx1D, 2Dx1D,
and 2Dx2D tensor multiplication (see torch_TensorOperator_(__mul__) in
TensorOperator.c).
> Doc: remove line saying that 4Dx2D tensor multiplication is supported.

- generic/Tensor.c
Fixes #361 
Returning the source makes no sense, this is likely a historical oversight. Cutorch does it correctly by returning self.
> return self in maskedCopy, make consistent with cutorch

- TensorMath.lua
I found this issue while debugging this (crazy) [problem](http://stackoverflow.com/q/33047651/1688185): the product of two zero matrices has NaN entries. This occurs with the default implementation when there is no BLAS support (interestingly there is - apparently - no problem with OpenBLAS).
Properly initializing the result tensor (that is involved in `res = beta x res + alpha x sum` operations behind the scenes) obviously solves the problem. By the way this is already done for [`torch.ger`](https://github.com/torch/torch7/blob/28de026/TensorMath.lua#L372-L378) via a precall.
At first I planned to extend the init hook as follow:
```Lua
init=function(arg)
return table.concat(
{
arg.__metatable.init(arg),
string.format("TH%s_resize1d(%s, %s->size[0]);", Tensor, arg:carg(), …
```
> TensorMath.lua: zero init result tensor

- lib/luaT/README.md
- lib/luaT/luaT.c
Patch allows for declaration of 'nested' modules/classes, e.g., `torch.class('A.b.c')`, where `b` is a module in package `A` and `c` is a submodule of `b`.
If a specified module path is invalid, error report will now indicate where said path goes wrong. By way of example: 
If module `c` is declared with path `A.b.c`, but `A.b` is not a valid module; then, error report will read as:
```lua
...: while creating metatable A.b.c: bad argument #1 (A.b. is an invalid module name)
```
Should likely check to ensure full backwards compatibility. 
cc: @andresy, @dominikgrewe
> patch to luaT.c allowing for nested modules

- lib/TH/THDiskFile.c
This makes the error message for pipefail suggest that out-of-memory is a possibility too.  I spent ages trying to figure out why gnuplot sometimes didnt work for me.  Now, if gnuplot fails, it will give a stack trace like:
```
/home/user/torch/install/bin/luajit: cannot open </usr/bin/gnuplot -persist > /dev/null 2>&1> in mode  w.  This might be because eg the executable doesn't exist, but it could also be because you are out of memory. at /home/user/git/torch7/lib/TH/THDiskFile.c:585
stack traceback:
[C]: at 0x7f1054b81e10
[C]: in function 'PipeFile'
/home/user/torch/install/share/lua/5.1/gnuplot/gnuplot.lua:134: in function 'getfigure'
/home/user/torch/install/share/lua/5.1/gnuplot/gnuplot.lua:736: in function 'filefigure'
/home/user/torch/install/share/lua/5.1/gnuplot/gnuplot.lua:754: …
```
> More informative error message for pipefile fail

- TensorMath.lua
- doc/maths.md
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
The `torch.median` and `torch.kthvalue` do not seem to operate as the docs say. This adds the tensor `torch.mode` operation and changes the docs of those 2 operations to match their current behaviour.
> Add torch.mode and fix median/kthvalue docs

- TensorMath.lua
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
- in place subtraction operators
- this addresses https://github.com/torch/torch7/issues/362
Use like this:
```
a = torch.Tensor(3,2):uniform()
b = torch.Tensor(3,2):uniform()
a:neg()           -- like a = -a,       but in-place
a:csub(1.5)       -- like a = a - 1.5,  but in-place
a:csub(b)         -- like a = a - b,    but in-place
```
> add :neg() :csub(tensor) :csub(scalar), inplace subtraction operators

- doc/maths.md
I've tried to fix some typos and to add examples.
On line 2118, [LAPACK convention] link is broken, but I couldn't find a
proper web page to fix it.
Thank you. :)
> Typo, Examples

- Tensor.lua
`tostring()` on a Storage prepends an unnecessary newline character (`\n`):
```
t7> print(tostring(torch.ones(1)))
1
[torch.DoubleTensor of size 1]
t7> print(tostring(torch.ones(1):storage()))
<-- removing this \n
1
[torch.DoubleStorage of size 1]
t7>
```
This pull request removes this newline, to make it consistent with `Tensor.__tostring__`. 
Each string also includes an unnecessary trailing newline, but I imagine removing this will annoy a lot of people.
> Remove the leading newline from Storage.__tostring__.

- lib/TH/generic/THTensorRandom.c
This fixes #418 by setting the accumulators to the proper type as suggested by @andresy 
The following code is now working as expected with `FloatTensor`s
```lua
do
p = torch.FloatTensor(100000):fill(1)
p:narrow(1, 50000 + 1, 50000):fill(1e-3)
p:div(p:sum())
N = 1001000
n = 0
c = torch.LongTensor(p:nElement()):zero()
c_ptr = c:data() - 1
tmp = torch.LongTensor()
for i = 1, 100 do
p.multinomial(tmp, p, N, true);
n = n + N
tmp:apply(function(i) c_ptr[i] = c_ptr[i] + 1 end)
end
actual = c:narrow(1, 50001, 50000):sum()
expected = n*p:narrow(1, 50001, 50000):sum()
print(actual, expected)
end
```
> Use proper precision for accumulators in multinomial

- generic/Tensor.c
- generic/TensorOperator.c
Following #441, this improves the error message containing Tensors by specifying the expected type.
I know that [these](https://github.com/torch/torch7/blob/5921fddc22a7581b11e4fe44fa80ca9239d6b7d4/generic/Tensor.c#L1114-L1119) messages may not be accurate sometimes: `LongStorage`s could be accepted when coming from the `new` function but not when coming from the `set` function. But due to the current state of `torch_Tensor_(set)`, I cannot be more precise. I will open a PR to fix `torch_Tensor_(set)` (and the corresponding error messages) asap.
> Improve Tensor creation error messages

- doc/tensor.md
- generic/Tensor.c
In Lua, explicitly calling `:free()` on a Tensor is currently buggy - it actually frees the THTensor struct itself  in C, making any future reference to it invalid (leading to segfaults). This patch makes `:free()` only act on the referenced storage, but preserves the THTensor struct intact (and also maintains the ref counter to 1) — the result: the user can free a tensor-referenced storage from Lua, but the THTensor struct itself will always be handled by the GC.
> tensor:free() should only free underlying storage.

- lib/TH/THDiskFile.c
- lib/TH/THFile.c
- lib/TH/THFile.h
- lib/TH/THFilePrivate.h
- lib/TH/THMemoryFile.c
When tensors size starts to exceed around 4GB the type long can’t hold this size anymore and torch.save/torch.load act unpredictably (due to the underlying c functions - fwrite etc). Reproduced when using convolutional neural networks for big image processing.
> Fixed large data storing and restoring 

- lib/TH/THDiskFile.c
- lib/TH/THFile.c
- lib/TH/THMemoryFile.c
Several days ago there was a commit that replaced `long` with `size_t` in THFile, THDiskFile and THMemoryFile. Because it is an unsigned type an overflow happened in several places. This commit fixes it.
> Fixed unsigned overflows in THFile

- doc/random.md
at #450 bamos pointed out that open bracket `[a,b[` is actually correct here  [(the code)](https://github.com/torch/torch7/blob/master/lib/TH/THRandom.c#L203).
I just changed it to `[a,b)` for better intuition
> [doc] math expression fix

- doc/tensor.md
- generic/Tensor.c
- lib/TH/generic/THTensor.c
- lib/TH/generic/THTensor.h
- test/test.lua
Returns true iff Tensor is set to argument Tensor. Specifically, this is
true iff tensor shares same storage as argument tensor, with same
storage offset and identical sizes and strides.
What do people think about including such a method?
> Add isSetTo: simple check for shared storage.

- doc/utility.md
Change torch.type -> torch.typename in corresponding example.
> Typo in documentation

- File.lua
This is, for example, relevant, when trying to load bytecode with Luajit 2.1 which was created with Luajit 2.0 - there is an incompatibility and previously the error would occur somewhere below (e.g. when trying to set upvalues) and give a less meaningful error message.
> Error messages when bytecode loading fails

- lib/TH/THMemoryFile.c
Comparison on line 486 (nBufferWritten > -1) sometime fails when size_t resolves to unsigned int.
> Make nBufferWritten signed for writing longs

- File.lua
- test/test_writeObject.lua
When serialization fails, it's hard to figure out what object can't be synchronized. Especially comes up in torch-threads. Any interest in this PR?
With this PR, you would now get the following error:
```
luajit: ...al/git/torch-distro/install/share/lua/5.1/torch/File.lua:115: Unwritable object <function>
at <?>.outer.theinner.baz.torch.cat
```
for this code
```lua
local torch = require 'torch'
local inner = {
baz = function(a) torch.somefunc() end
}
local outer = {
theinner = inner
}
function evil_func()
outer.prop = 1
end
torch.save('saved.t7', evil_func)
end
```
> Track and print the serialization 'stack trace' on failure

- TensorMath.lua
- doc/maths.md
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
This is an implementation of k-selection: returning the `k` highest or lowest values in a selected dimension.
For sorted results, it is functionally equivalent to:
```
local function topKViaSort(t, k, dim, dir)
local sorted, indices = t:sort(dim, dir)
return sorted:narrow(dim, 1, k), indices:narrow(dim, 1, k)
end
```
This torch7 CPU implementation I provide here actually just maps to the above (in effect, always sorting the results). It could be improved to use selection to find the kth element and a second scan at some point.
I am adding this as a simple, albeit functional placeholder because I have an efficient, optimized GPU cutorch implementation of this based on radix selection. I need this in torch7 in order to allow the torch.topk() bindings to work. @soumith and @andresy are aware …
> k-selection implementation: torch.topk

- cmake/TorchPackage.cmake
- lib/TH/CMakeLists.txt
- lib/luaT/CMakeLists.txt
static libraries no longer built by default
=> halves the build time
> static libraries no longer build by default => builds faster

- doc/maths.md
- Matlab -> MATLAB (This is how the company spells it)
- mathematic -> mathematical
- "sizes must be relevant" -> "sizes must be conformant" (this is more or less the standard term used when defining matrix multiplication)
> maths.md: minor wording changes

- TensorMath.lua
- doc/maths.md
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
This makes a number of changes to both lua and C code to facilitate the second return value of a torch.max(input) call without specified dimension to be a LongTensor(default) that gives the indeces of the argmax of an input tensor. The C interface for the relevant functions(THTensor_(minall)/(maxall)) is changed and therefore it is not backward compatible (e.g. see line 2274 @ lib/TH/generic/THTensorMath.c). We can keep the original functions if requested in which case C interface would be compatible with earlier versions as well.
> Adding argmax index as second return value to max/min calls without specified dimension

- TensorMath.lua
- doc/maths.md
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
> Revert "Adding argmax index as second return value to max/min calls without specified dimension"

- CmdLine.lua
Lua 5.2 does not support %F and %T, looks like it. Even though they are valid formatting in http://man7.org/linux/man-pages/man3/strftime.3.html
> Lua 5.2 fix for date/time formatting in CmdLine

- lib/TH/THDiskFile.c
The previously added longSize field was only initialised in DiskFile and
not in PipeFile. This meant uninitialised memory was used in PipeFile
construction.
> Initialise longSize in PipeFile

- CmdLine.lua
Fixes https://github.com/torch/torch7/issues/528
> fixing Cmdline:log to get the print function lazily

- lib/TH/generic/THTensorMath.c
- test/test.lua
Fix for "torch.all only returns true if all numbers in the tensor are odd #517"
> Fix for issue #517: torch.all

- torchcwrap.lua
If you happen to pass in a big table to torch.cat and you were near the end of the lua stack you could corrupt memory. This fix tells lua to grow the stack if it needs to.
> Fixing a lua stack overflow.

- lib/TH/THGeneral.h.in
- lib/TH/THLapack.h
- lib/TH/generic/THTensorMath.c
Two commits in this PR create a generic facility for passing cleanup code to various error macros that do not return. The third commit adds clean-up to various `APPLY` macro uses in `THTensorMath.c`.
> Improve memory cleanup handling and fix memory leaks

- doc/storage.md
In practice the storage is only [ref-counted](https://github.com/torch/torch7/blob/a8684284708badfba04723febd9247385cb2dcfc/generic/Storage.c#L74) in such a case.
> doc/storage: add precisions for ptr, size mode

- cmake/TorchPackage.cmake
.. "if ($src)" does not work if $src i a macro, as cmake does not consider macro argument to be a variable (!). So only the case that had an upper scope variables named $src and luasrc worked before. 
Also, C linker language specified for sources as CMake gets lost if all sources are .cu CUDA files
So now cunn can use ADD_TORCH_PACKAGE  macro (used to break on both issues above)
> Fixed a bug in TorchPackage macro arguments test

- cmake/TorchPackage.cmake
Reverted previous change - current code works w/o it, should it be necessary for some modules, can be dome on modules side.
> Removed C linkage setting

- File.lua
- doc/serialization.md
`torch.load32()` and `torch.load64()` have been replaced by `torch.load(fileName, 'b32')` and `torch.load(fileName, 'b64')` as discussed in #540.
> Add support for loading data saved on 32/64 bit OS

- lib/TH/generic/THTensor.c
- test/test.lua
The case of self->storage == NULL was not checked, so any two Tensors
with no storage would effectively appear to be shared with each other.
Added a test to prevent regressions.
> Fix a bug in :isSetTo

- TensorMath.lua
- lib/TH/generic/THTensorRandom.c
- lib/TH/generic/THTensorRandom.h
- test/test.lua
Now it also accepts a tensor of probabilities instead of a single Lua number.
Added a test that checks that the output is binary.
> Extend torch.bernoulli()

- TensorMath.lua
Fixes #548.
If this is merged [/torch/cutorch/blob/master/test/test.lua#L2597](https://github.com/torch/cutorch/blob/master/test/test.lua#L2597) should be modified to torch.cat, instead of torch.CudaTensor.cat.
> Fix torch.cat for table arguments

- .travis.yml
- CMakeLists.txt
- TestSuite.lua
- Tester.lua
- doc/tester.md
- init.lua
- rocks/torch-scm-1.rockspec
- test/test.lua
- test/test_Tester.lua
- test/test_qr.lua
- test/test_sharedmem.lua
- test/test_writeObject.lua
This should bring a lot of benefit to code that uses torch.Tester (totem will
eventually become deprecated). Note that torch.Tester and totem.Tester once
shared the same code - this change brings it full circle.
At a glance, extra functionality includes:
- A general equality checker that accepts many different objects.
- Deep table comparison with precision checking.
- Stricter argument checking in using the test functions.
- Better output.
- torch.Storage comparison.
- Extra features for fine-grained control of testing.
> Replace torch.Tester with totem.Tester + extra stuff.

- TensorMath.lua
- test/test.lua
Sorry for breaking torch.cat{} in my previous pull request #582, also broke torch.cat{1}, torch.add{} etc. resulting in a segmentation fault.
Rewrote the function to check for the table being empty, and put it in a function to allow it to use the default tensor if it is empty or contains an invalid tensor. Also added additional unit tests.
> Fix broken torch.cat{} and added tests

- Tester.lua
after the recent Tester refactor, sys was a hard dependency on torch. making it optional.
> making sys optional

- rocks/torch-scm-1.rockspec
cc: @borisfom 
for now removing the sys dependency. I've already made the require behind a pcall in an earlier commit, so the dependency is very much optional.
> removing sys dependency for now

- lib/TH/generic/THTensorRandom.c
- test/test_Multinomial.lua
Basically forces all the cumulative distribution to DoubleTensor and all the intermediate states to doubles as well whatever the input probs type.
Also added a perf+rare-event test based on #418 @andresy's  example for further testing but I didn't notice any major slowdown.
> Fix multinomial regression.

- lib/TH/generic/THTensorMath.c
xmax, xmin and step are accreal. Therefore, computations are carried out in both int and double logic. The separate division does introduce a bug when int logic is used.
```lua
th> torch.range(1, 25, 5, 'torch.LongTensor')
1
6
11
16
21
26
[torch.LongTensor of size 6]
th> torch.range(1, 25, 5, 'torch.FloatTensor')
1
6
11
16
21
[torch.FloatTensor of size 5]
```
```lua
th> torch.range(1, 25, 5, 'torch.FloatTensor')
1
6
11
16
21
[torch.FloatTensor of size 5]
th> torch.range(1, 25, 5, 'torch.LongTensor')
1
6
11
16
21
[torch.LongTensor of size 5]
th> torch.range(1, 25, 5, 'torch.DoubleTensor')                                                      
1
6
11
16
21
[torch.DoubleTensor of size 5]
th> torch.range(1, 25, 5, 'torch.IntTensor')                                                         
1
6 …
```
> Fix bad size evaluation

- generic/Storage.c
- generic/Tensor.c
- generic/luaG.h
- lib/luaT/luaT.c
- lib/luaT/luaT.h
This shouldn't change any behavior when compiled with Lua < 5.3 or LuaJIT.
Will post the corresponding change to cwrap. This works fine independent of that, but some functions like :fill() on LongTensor won't properly support 64-bit inputs until cwrap is updated.
> Lua 5.3 integer support

- init.lua
- test/test.lua
This reverts the "enclosed" class matching introduced in 9c75e57, which
broke matching against patterns. In contrast to the original implementation,
non-pattern strings are always matched fully against type names to minimize
surprises caused by e.g. common prefix.
> Revert to pattern matching in isTypeOf()

- lib/TH/generic/THTensorLapack.c
Hi, this PR removes an unnecessary rank check in the `potrs` code.
To illustrate why I think this is unnecessary, consider the following example.
```Lua
A = torch.Tensor({
{1.2705,  0.9971,  0.4948,  0.1389,  0.2381},
{0.9971,  0.9966,  0.6752,  0.0686,  0.1196},
{0.4948,  0.6752,  1.1434,  0.0314,  0.0582},
{0.1389,  0.0686,  0.0314,  0.0270,  0.0526},
{0.2381,  0.1196,  0.0582,  0.0526,  0.3957}})
B = torch.Tensor({
{0.6219,  0.3439,  0.0431},
{0.5642,  0.1756,  0.0153},
{0.2334,  0.8594,  0.4103},
{0.7556,  0.1966,  0.9637},
{0.1420,  0.7185,  0.7476}})
chol = torch.potrf(A)
torch.potrs(B, chol)
torch.potrs(torch.cat({B,B}, 2), chol)
```
`cat(B,B)` fails the rank check, but this is irrelevant and
shouldn't result in an error.
```Lua
th> torch.potrs(B, chol)
-94.2808   -9.3526 -121.8567 …
```
> Remove unnecessary rank check in potrs call.

- lib/TH/generic/THTensorMath.c
- test/test.lua
Allow end < start in linspace and logspace (no mathematical reason to forbid
this, and it makes it match numpy behaviour).
Also don't raw-resize tensor unnecessarily. This makes it work with
non-contiguous tensors (e.g., can now do a range on a slice of a tensor).
> Improvements to torch.{linspace, logspace, range}.

- DiskFile.c
- doc/diskfile.md
- lib/TH/THDiskFile.c
- lib/TH/THDiskFile.h
The noBuffer function disables read and write buffering via setvbuf.
This is particularly useful for random reads from files on networked storage, which otherwise results in much larger network transfers.
> Add DiskFile:noBuffer()

- Tester.lua
Loading the sys package can cause a deadlock in some OpenBLAS
configurations when multiple Torch threads require sys (via the torch
package) at the same time.
Depends on torch/sys#8
> Only require sys.colors from sys

- lib/TH/THGeneral.h.in
- lib/TH/THGenerateAllTypes.h
- lib/TH/THGenerateFloatTypes.h
- lib/TH/THGenerateIntTypes.h
- lib/TH/THLogAdd.c
I have not tested this change with libraries other than `torch7` itself. From a search though our internal codebase, I believe that whatever code does break (e.g. in `cunn`) is actually incorrect in its current form and needs to be fixed (usually something like `float x = -THInf;`, which needs to become `float x = -FLT_MAX;`).
What do you think?
> Make THInf type-specific

- lib/TH/generic/THTensorLapack.c
Per discussion at [https://github.com/torch/torch7/issues/227](https://github.com/torch/torch7/issues/227), we can remove junk values from right-singular vectors matrix in SVD when using the 'S' option, to reduce memory footprint.
> Remove junk values from right-singular vectors matrix in SVD

- File.lua
- test/test_writeObject.lua
This extra slot comes from [here](https://github.com/torch/torch7/blob/814836bb3115fa0a0b3f3d6982122e08f9f6530d/lib/TH/THMemoryFile.c#L230). IMHO we should get rid of it in the context of `serialize` / `serializeToStorage` so that archives are identical to those produced by `save`.
> File: get rid of extra NULL character (serialize)

- lib/TH/THGeneral.c
It will crash application when calling _msize(NULL) on windows xp.
> Fix _msize crash on windows xp

- TensorMath.lua
- doc/maths.md
- generic/TensorOperator.c
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
To resolve https://github.com/torch/torch7/issues/607, I added `torch.fmod()`, `torch.cfmod()` for computing remainder of division (rounded towards zero) and `torch.remainder()`, `torch.cremainder()` for computing `a % b = a - b * floor(a/b)`.
1. `torch.fmod()` and `torch.cfmod()` are the same as `torch.mod()` and `torch.fmod()`.
2. `torch.remainder()` and `torch.cremainder()` compute remainders by `a - b * floor(a/b)` and it will return `nan` if `b == 0`. The function `remainder()` in the math library computes by `a - b * round(a/b)`. In my laptop, `torch.remainder()` is faster than `torch.fmod()`.
```lua
th> a = torch.Tensor(10000, 10000):uniform(-10, 10);
[0.9528s]
th> b = torch.fmod(a, 2);
[1.0508s]
th> c = torch.remainder(a, 2);
[0.5180s]
```
3. The tensor operator uses …
> Add fmod(), remainder(), remove mod() and fix tensor operator % behavior

- Generator.c
- test/test.lua
This implements read/write naively as a block of bytes for a given torch.Generator (in the style of set/getRNGstate, which use memcpy).
> Make torch.Generator serializable

- generic/TensorOperator.c
Before this change, the expression `-luaL_checknumber(L, ...)` has type `double`, and its value may not be representable as `real`, leading to undefined behaviour. After this change, the unary negation is applied to a value of type `real`, and the arithmetic promotion and conversion rules give this well-defined behaviour.
> [TensorOperator.c] Make unary negation expression have real type, not double

- lib/TH/generic/THTensorMath.c
`addmm` didn't support properly non-contiguous result tensors.
The goal of this part of the code is to copy the contents of `r_` into `r__` such that `r__` contains the transpose of `r_` contiguous in memory.
The way it was doing was by considering `c_inv = torch.Tensor(c:size(2),c:size(1)):copy(c)`, which doesn't transpose the tensor but only change its shape.
This problem was introduced in https://github.com/torch/torch7/commit/0d534e64f5569fea2992a2754f0b87e27b3c1d8c .
I'll add more unit tests later if you want.
Should fix https://github.com/torch/torch7/issues/671
Also, something similar should be added to `cutorch`.
> Fix addmm for non-contiguous result tensor

- Tester.lua
Previously: if early abort was enabled, then it would abort on any disabled tests.
> torch.Tester early abort and disable: make them work when used together

- CmdLine.lua
- doc/cmdline.md
Allows the user to provide his own file (for example in a different mode or from a different source).
> Make CmdLine:log check whether file is a file descriptor, before creating a new file

- lib/TH/generic/THTensorMath.c
No longer cloning input tensor nor using tensor operations but computing destination bin index directly in TH_TENSOR_APPLY() block and ensuring that bin index does not exceed nbins-1.
> Fix torch.histc problem #718

- generic/luaG.h
Fixes #706 
```lua
t = torch.LongTensor(1)
str = '10151188881778163'
t[1] = str
print(str)
print(t:data()[0])
```
Output:
```bash
10151188881778163
10151188881778163LL
```
> fixing a truncation bug when numbers are given as strings

- File.lua
This seems like a needed change, now that we have LuaJIT 2.1, 2.0, Lua 5.2 and soon Lua 5.3 used by torch users.
The models which are serialized usually have no functions, but occasionally have some functions which usually are not needed.
Fixes https://github.com/torch/torch7/issues/641 and #741
> changing function load errors to warnings

- lib/TH/THAllocator.c
- lib/TH/THAllocator.h
* `TH_ALLOCATOR_MAPPED_FROMFD` uses an existing file descriptor for
mapping (and steals it)
* `TH_ALLOCATOR_MAPPED_KEEPFD` doesn't close the file descriptor
until the mapping is freed
* `TH_ALLOCATOR_MAPPED_UNLINK` unlinks the file immediately after
mapping it to memory
Also, now it's using `fstat` to check the file size (instead of `lseek`, which alters the fd state).
> Add new flags for THMapAllocator

- lib/TH/THGeneral.c
- lib/TH/THGeneral.h.in
`THSetErrorHandler` still modifies per-thread pointers, but `THSetDefaultErrorHandler` allows to set a handler that's used by all threads that haven't specified any function.
> Allow changing the default error handler for all threads

- lib/TH/THGeneral.c
- lib/TH/THGeneral.h.in
- utils.c
Expose omp_set_num_threads and similar APIs through the TH lib. This
means a third-party libaries using TH don't need to be compiled with
OpenMP support just to control the number of TH OMP threads.
> Expose OpenMP num threads through TH lib

- doc/tensor.md
Original call to maskedCopy() only included y, not the mask. Update added the mask to the first argument.
> Updated maskedCopy example #1

- lib/TH/THDiskFile.c
On FreeBSD, int32_t is defined in stdint.h as well. this change fix the problem. Since stdint.h is part of Posix, it should be safe to include it unconditional.
> Fix compile error on freebsd

- lib/TH/THRandom.c
- test/test.lua
Current implementation was broken. See numpy:
https://github.com/numpy/numpy/blob/c90d7c94fd2077d0beca48fa89a423da2b0bb663/numpy/random/mtrand/distributions.c#L691
for a correct implementation, which we adopted here.
Test Plan:
- Add unit test, stolen from cutorch
> Fix implementation of logNormal

- lib/TH/generic/THTensorLapack.c
- lib/luaT/luaT.c
Hi,
1. THTensorLapack.c : to be consistent with THLapackCheckWithCleanup
2. luaT.c : `lua_pushstring()` returns `const char *` instead of `void `since lua 5.2
Thanks,
> 2 trivial changes to compile with msvc

- lib/TH/generic/simd/simd.h
A fix for issue #807  - compilation on Raspberry PI without NEON ( BCM2708 chip)
> Fixed compilation on Raspberry PI without NEON, fixes #807

- lib/TH/THVector.c
- lib/TH/generic/THVectorDispatch.c
- lib/TH/generic/simd/simd.h
- lib/TH/vector/VSX.c
Added support for the fill, diff, scale, mul and add functions using
PPC CPU vector instructions. These are used in place of the versions
of these functions written for x86, when compiled on PPC.
This fixes a compile failure on PPC
> Add support for VSX vector instructions on PPC

- TensorMath.lua
- doc/maths.md
- lib/TH/generic/THTensorMath.c
- lib/TH/generic/THTensorMath.h
- test/test.lua
[ Description ]
When a tensor contains multiple images, and one need to calculate the histogram of each image in this two dimension tensor. If using the original `torch.histc` function, should have to write a loop to calculate them. This way is not effective enough. So I write a new function named by `torch.histc2` to output the histogram tensor only once, the input is the 2D tensor, each row indicates an image, the default bins is 100 as the original `histc`, calculate the histogram along the last dimension of input tensor.
[ Code Change ]
* In `lib/TH/generic/THTensorMath.c`, add a new math function `void THTensor_(histc2)`
* In `lib/TH/generic/THTensorMath.h`, add a statement for `void THTensor_(histc2)`
* In `TensorMath.lua`, add the `histc2` for `wrap`
* In `test/test.lua`, add a …
> Add a new function bhistc to calculate histogram of batch of images only once

- lib/TH/THGeneral.c
Some error handlers may not have any data associated with them
> Fix condition for threadArgErrorHandler

- lib/TH/generic/THTensorCopy.c
Avoid casting TH_HALF to TH_HALF, as it breaks msvc.
> Fix THHalf issues with MSVC.

- lib/TH/generic/simd/simd.h
`__NEON__` is an ISA indicator instead of architecture indicator.
> simd.h: really fix the arm64 (i.e. Aarch64) build

- lib/TH/THHalf.c
Verified that at least for GCC 4.47 this generates identical code.
> Avoid strict aliasing warning in float/half conversions.

- lib/TH/THHalf.c
This change was approved by NVIDIA Legal, and I am authorized to make the change on behalf of the company.
> Remove erroneous proprietary license header

- lib/TH/generic/THTensor.c
- lib/TH/generic/THTensor.h
- lib/TH/generic/THTensorMath.c
These methods are useful from C because they don't require constructing
THLongStorages to wrap the sizes and strides, which can lead to leaked
memory in case of an error. Instead the sizes and strides can be
represented on the stack using standard C long arrays.
We already expose `rawResize` in THC for use with MAGMA.
> Expose rawSet and rawResize as resizeNd and setStorageNd

- lib/TH/generic/THTensor.c
- lib/TH/generic/THTensor.h
Unsqueeze inserts a singleton dimension. Unlike view, it doesn't require
the tensor to be contiguous.
> Add unsqueeze1d to TH

- lib/TH/CMakeLists.txt
- lib/TH/generic/simd/simd.h
A more proper fix of #924
In addition to #924, makes sure that we dont hit a particular GCC bug
> fix AVX2 detection bugs

- lib/TH/THTensorApply.h
- lib/TH/generic/THTensorMath.c
- test/test.lua
I just did `sum`, `prod`, `mean`, `max`, and `min` for now, but you can do a bunch of the other pointwise reductions like this too. 
before:
```
th> t = torch.randn(64,1024,1024)
[5.6855s]
th> t:max(1);
[1.7969s]
th> t:max(2);
[0.9834s]
th> t:max(3);
[0.1487s]
th> t:sum(1);
[1.5895s]
th> t:sum(2);
[0.9665s]
th> t:sum(3);
[0.1610s]
```
after:
```
th> t = torch.randn(64,1024,1024)
[5.7820s]
th> t:max(1);
[0.3097s]
th> t:max(2);
[0.2392s]
th> t:max(3);
[0.1456s]
th> t:sum(1);
[0.1985s]
th> t:sum(2);
[0.2219s]
th> t:sum(3);
```
I think the optimizations for `max` and `min` will conflict with the TH_TENSOR_APPLY improvements in https://github.com/torch/torch7/pull/852, but we can always add special macros for this purpose if we want to keep the max and min optimizations. That new macro could …
> Speed up reductions on non-contiguous dimensions

- lib/TH/generic/THTensorMath.c
The recent refactoring of THTensorMath.c uses C99's _Pragma. This isn't supported by MSVC, which uses __pragma. I confirm this builds on MSVC.
> C99 cleanup broke MSVC

- lib/TH/generic/THTensorMath.c
- test/test.lua
- Fixes  default dimension check from -2 to use `TH_INDEX_BASE`. I think master probably fails on PyTorch.(haven't checked). 
- Also added tests for cat when no dimension is specified (Similar to what is happening in https://github.com/torch/cutorch/pull/719)
- As done with cutorch, changed the variable name to make life easier when debugging this function.
> Fix dimension check for cat

- lib/TH/CMakeLists.txt
Hi,
The AVX/AVX2 test for msvc can pass without /arch:AVX or /arch:AVX2 compiler options. And FindSSE.cmake will test with no flags at first, so the empty flag is returned. However the `__AVX__` and `__AVX2__` macro will only be defined automatically when /arch:AVX and /arch:AVX2 options are specified.
I am not sure about gcc or clang's behavior, so I did not change FindSSE.cmake directly. Instead I added those must have options directly in SET_SOURCE_FILES_PROPERTIES.
Thanks,
> add /arch:AVX /arch:AVX2 explicitly for msvc so it compiles on windows

- TensorMath.lua
- doc/maths.md
- init.lua
- lib/TH/generic/THTensorCopy.c
- lib/TH/generic/THTensorRandom.c
- lib/TH/generic/THTensorRandom.h
- test/test.lua
- test/test_aliasMultinomial.lua
This allows for faster sampling from a multinomial distribution using the __Alias__ method which is described in this [paper](http://www.tandfonline.com/doi/abs/10.1080/00031305.1979.10482697).
It allows almost `5x` speed in sampling than `torch.multinomial`. To see the difference on your machine run ` th test/test_aliasMultinomial.lua`
> Implementation of Alias Multinomial for faster Multinomial sampling
