torch/torch7

TensorMath.lua, doc/maths.md, lib/TH/generic/THTensorMath.c, lib/TH/generic/THTensorMath.h, test/test.lua
Completely analogous to cmul/cdiv.
=> Element-wise pow function cpow

TensorMath.lua, doc/maths.md, lib/TH/generic/THTensorMath.c, lib/TH/generic/THTensorMath.h, test/test.lua
- addbmm is a batch MM + reduce add
- baddbmm is a batch MM + batch add
=> Renamed baddmm -> addbmm; added baddbmm.

lib/TH/generic/THTensorMath.c, test/test.lua, test/timeSort.lua
Rebase of #147  in a single commit. Conversation started there, continuing here.
=> Qsort from reference article -- rebased

lib/TH/THGeneral.c, lib/TH/THGeneral.h.in
=> Revert "Add file and line number to THError."

File.lua, test/test_writeObject.lua
=> (slightly) more flexible serialization system

.travis.yml
Travis was constantly noisy and with false-positives. Also, it was completely invalid for PRs, and did not actually build the PR branch (but built master).
This PR fixes all of that, and also now travis correctly errors out on tests failing.
=> fixing travis to properly build and test

lib/TH/generic/THTensorMath.c, test/test.lua
=> fixed maskedCopy to accept src with size greater than the num of ones in mask

generic/Storage.c, init.c
Allows passing in an allocator as the first parameter when creating a storage.
=> Pass optional allocator to storage.

TensorMath.lua, doc/tensor.md, lib/TH/generic/THTensorMath.c, lib/TH/generic/THTensorMath.h, test/test.lua
Functions to read to / write from tensor, selecting one element from
each slice along the specified dimension.
=> Add scatter and gather operations.

lib/TH/THAtomic.h
Needed to correctly link C and C++ code.
=> Annotate function in THAtomic.h with TH_API.

lib/TH/generic/THTensorLapack.c, test/test.lua
This should be solving #208  and #237
=> avoid unnecessary transpose in lapackClone

TensorMath.lua, doc/maths.md, lib/TH/generic/THTensorMath.c, lib/TH/generic/THTensorMath.h, test/test.lua
Add cmin & cmax operation for element-wise min and max between two
tensors and between a tensor and a scalar.
=> Element-wise min and max operations.

lib/TH/generic/THTensorLapack.c, test/test.lua
fixes for other cases of lapack function calls with result tensors
clean up
replace manual contiguous check
=> fix two more cases of tranpose check in lapack.

TensorMath.lua, doc/maths.md, lib/TH/generic/THLapack.c, lib/TH/generic/THLapack.h, lib/TH/generic/THTensorLapack.c, lib/TH/generic/THTensorLapack.h, test/test.lua
Lapack has optimized functions for solving systems of equations Ax = b in which the matrix A is upper- or lower-triangular. This pull request exposes this function through a new function torch.trtrs.
=> Exposing the lapack function trtrs which solves triangular systems of linear equations.

doc/cmdline.md, doc/diskfile.md, doc/file.md, doc/index.md, doc/maths.md, doc/memoryfile.md, doc/pipefile.md, doc/random.md, doc/serialization.md, doc/storage.md, doc/tensor.md, doc/tester.md, doc/timer.md, doc/utility.md, mkdocs.yml
This PR results in this http://torch7.readthedocs.org/en/readthedocs/tensor/index.html .
=> readthedocs

lib/TH/generic/THTensorMath.c
Fixes a bug I introduced in Tensor:index for some contiguous tensors.
Previously, the code assumed that for contiguous tensors, stride[0]
is the product of size[1] * size[2] * ... size[nDim-1]. This is not
necessarily the case if the size of the first dimension is 1.
For example, contiguous 3x2x7 and 4x2x7 tensors must have stride 14x7x1, but
a 1x2x7 tensor may have any stride in the first dimension (e.g. 99x7x1).
A correct way to determine the effective "row size" for Tensor:index
is to take the nElement / size[0].
=> Fix Tensor:index for some tensors with the first dimension of size 1

lib/TH/THLapack.h, lib/TH/generic/THTensorLapack.c
clean-up and simplify cloning/collection logic
remove now unused cloning functions
adopt trtrs to new clean setup
=> clean-up and simplify cloning/collection logic

doc/maths.md
=> correct copy-paste mistake in documentation

lib/TH/THGeneral.c
Contribution from @colesbury
Multithreaded Torch programs that do many small THAllocs were
encountering contention on updating heapSize. Instead, keep track of
allocations and frees in a thread-local variable, heapDelta, and only
update the global heapSize when heapDelta exceeds +/- 1MB.
=> Batch updates to global heapSize

TensorMath.lua, doc/maths.md, lib/TH/generic/THLapack.c, lib/TH/generic/THLapack.h, lib/TH/generic/THTensorLapack.c, lib/TH/generic/THTensorLapack.h, test/test_qr.lua
Could maybe do with some more tests e.g. single and double precision, passing the result tensor, non-square matrices, but everything seems to work.
=> LAPACK ormqr routine

TensorMath.lua, doc/maths.md, lib/TH/generic/THTensorLapack.c, lib/TH/generic/THTensorLapack.h, test/test.lua
Patch finishes partial implementation of LAPACK function potri and adds test/doc. Also introduces minor (grammatical) changes to test/doc for potrs/potrf.
=> Exposing LAPACK function potri

lib/TH/generic/THStorage.c
=> hard error on unresizable storages being resized

doc/memoryfile.md
Fixed a few typos in the memoryfile documentation.
=> Fixed typos in memoryfile doc

File.lua, doc/file.md, doc/serialization.md
also improved documentation for File:referenced()
=> added referenced option in torch.load() and torch.save()

doc/tensor.md, generic/Tensor.c, lib/TH/generic/THTensorMath.c, lib/TH/generic/THTensorMath.h, test/test.lua
Added function 'indexAccum' that is similar to 'indexCopy' but instead of setting each value by index in dest, it adds the value to the existing value at the index in dest.
=> Added indexAdd

rocks/torch-scm-1.rockspec
parallel build => builds faster
=> parallel build => builds faster

doc/maths.md
Also fixed some formatting errors like trailing whitespace and tabs.
=> Adding doc for torch.sign()

doc/utility.md, init.lua, lib/luaT/README.md, lib/luaT/luaT.c, lib/luaT/luaT.h
allows class creation in a local namespace, while being backward-compatible
with luaT_newmetatable.
=> introduced luaT_newlocalmetatable.

doc/storage.md, doc/tensor.md
* Add Storage creation from pointer (clarify this error #166 )
* Clarify creation of LongTensor from LongStorage
* Clarify use of torch.data asnumber option
=> Tensor and Storage doc update

lib/TH/cmake/FindLAPACK.cmake
Done for the installer, but useful in general. Also, my Emacs deletes trailing whitespace on save :)
=> Detecting LAPACK on the system with LAPACKless OpenBLAS

doc/maths.md
Yes, I know I'm affected by OCD...
Cleaned up to `clamp()`, which was missing proper formula layout.
=> First update of math.md

File.lua, test/test_writeObject.lua
=> File.lua: fix undefined debug function

lib/TH/THDiskFile.c
=> THDiskFile: fix incompatible pointer types warning

ROADMAP.md
environement > environment
compatibilty > compatibility
emabarassingly > embarrassingly
unnecesasrily > unnecessarily
lighweight > lightweight
curcial > crucial
existance > existence
=> Fix spelling mistake in Roadmap.md

File.lua, test/test_writeObject.lua
=> Fix upvalue binding during serialization

.travis.yml, test/test_writeObject.lua
also, added guards around test for lua51
=> fixing travis build for writeObject tests

TensorMath.lua, doc/maths.md, generic/TensorOperator.c, lib/TH/generic/THTensorMath.c, lib/TH/generic/THTensorMath.h, test/test.lua
* added torch.mod and torch.cmod
* added overloaded lua operator % for modulo operation
* fixed a bit of existing documentation
=> Added torch.mod and torch.cmod functions

doc/maths.md
doc tweak for in-plcae pow(n, x)
=> doc tweak for in-plcae pow(n, x)

init.lua
as discussed with ronan, replacing the clunky and obsolete include(...) with require('torch. ...')
=> replacing include with require

lib/TH/generic/THTensorMath.c, test/test.lua
=> torch.topk: use quickselect + quicksort

lib/TH/generic/THTensorMath.c
fixes https://github.com/torch/torch7/issues/355
=> only check isnan for float types

File.lua, test/test_writeObject.lua
* New Api is File:writeObject(object, debugname, hook)
* Backward-compatible
* Functionality: modifies objects to serialize on-the-fly before saving them while keeping track of the File:writeObject(...) nice reference-sharing. Useful when we want to save an object under a certain package config, and load it under another.
=> Add a hook to File:writeObject

TensorMath.lua, doc/maths.md, lib/TH/THMath.h, lib/TH/generic/THTensorMath.c, lib/TH/generic/THTensorMath.h, test/test.lua
=> Add math functions trunc, frac, rsqrt, lerp

cmake/TorchPackage.cmake
=> Added recognition of CUDA sources in ADD_TORCH_PACKAGE

TensorMath.lua
Fixes from discussion with @dominikgrewe regarding #583. I hope everything is correct now. :)
=> Fix stack cleanup in torch_istensorarray

lib/luaT/luaT.c
#610 
For binary operators, follow the original Lua behavior. (http://www.lua.org/manual/5.1/manual.html#2.10.1)
First, try the first operand. If its type does not have a metatable defining a handler for such operation, then try the second operand.
=> separate handler for binary/unary operators in luaT

lib/luaT/luaT.c
`luaT_lua_pointer` didn't check for overflows when converting pointers, and it used a signed long type, that could overflow and stay negative even after a cast to double. This addresses torch/threads#55.
=> Check for overflows when converting pointers in luaT

lib/luaT/luaT.c
I came across more segfaults when debugging threads. Apparently there's more of this conversion stuff 😕
=> Fix pointer to long conversions in luaT

lib/TH/generic/THStorage.c
This is a pre-diff that's needed to fix cutorch's THCudaHostAllocator_realloc which at the moment has a bug where it does not copy the old memory over to the new memory.
https://github.com/torch/cutorch/blob/master/lib/THC/THCAllocator.c#L21-L31
cc: @tudor
=> allow THAllocator to have a NULL realloc

lib/TH/THRandom.h, lib/TH/generic/THStorage.h
These were introduce when adding these two features to TH: #13 and #213
=> Remove some warning when compiling TH

.travis.yml
Adds one OS X job, luajit2.1 with clang.
=> Add OS X to travis builds

lib/TH/generic/THTensorMath.c
I'm really sorry about that, but I think I introduced a memory leak in https://github.com/torch/torch7/pull/672
This should address the leak, but please someone double check in case I'm missing something.
=> Fix memory leak in addmm

lib/TH/THGeneral.c
Hi there,
i made torch compile and run on FreeBSD.
Cheers,
tpltnt
=> FreeBSD port

lib/TH/THAtomic.c, lib/TH/THAtomic.h
Added the missing long version for atomic set. I'm adding an atomic counter in `tds` and adding support for that in `threads`, this is needed for that.
=> added THAtomicSetLong

lib/TH/generic/THTensorMath.c
=> fix "macro redefined" warning (th_isnan)

generic/TensorOperator.c
fixes https://github.com/torch/torch7/issues/665
=> fixing division / to be consistent with true division and not mul(1/a)

lib/TH/generic/THBlas.c
See: https://github.com/torch/nn/pull/898
=> fix gemm bug when beta = 0

lib/luaT/CMakeLists.txt
Imported from Debian package.
https://anonscm.debian.org/cgit/debian-science/packages/lua-torch-torch7.git/tree/debian/patches/luaT-cmake-add-version
=> cmake: add soversion for luaT

lib/TH/CMakeLists.txt
=> cmake: add soversion for libTH

doc/random.md
No new content. Just standardizing the formatting of the numbers and equations in the random docs.
=> clean up equations in documentation

test/test.lua
According to https://github.com/torch/torch7/issues/627
=> test: fix 32-bit system abs test failure.

lib/TH/generic/THVectorDispatch.c
This fix the build when I built torch in NVidia JETSON
=> Fix build when NEON is supported

test/test.lua
=> Fix error when run torch.test multi times

test/timeSort.lua
Hi,
Minor change to make timeSort.lua work on windows.
Thanks,
=> change timeSort test to work on windows

lib/TH/THAllocator.c
fixes https://github.com/torch/torch7/issues/809
=> fix bug in mmaping

lib/TH/THGeneral.c, lib/TH/THGeneral.h.in, lib/TH/generic/THVector.h, lib/TH/generic/THVectorDispatch.c
Fixes some compiler warnings.
(see http://stackoverflow.com/questions/416345/is-fvoid-deprecated-in-modern-c-and-c)
=> Fix no-arg function prototypes

lib/TH/generic/THTensorLapack.c
Also, linear system solvers can now accept vectors (they had to be reshaped to Nx1 matrices before).
=> Add more size checks and improve some LAPACK error messages

lib/TH/THTensorApply.h, lib/TH/THTensorDimApply.h
Not sure if this would be beneficial to others, up to you.
=> Add some documentation for APPLY and DIM_APPLY macros

lib/TH/CMakeLists.txt, lib/TH/generic/simd/simd.h
Fixes https://github.com/torch/torch7/issues/876
Thanks to @ius for the hint.
=> use __get_cpuid when available

lib/TH/THGenerateAllTypes.h, lib/TH/THGenerateFloatTypes.h, lib/TH/THGenerateHalfType.h, lib/TH/THGenerateIntTypes.h
Also cleans up `THGenerateAllTypes.h` to simply include `THGenerateFloatTypes.h` and `THGenerateIntTypes.h`. This is similar to what is happening in cutorch.
=> Macros to convert between real and accreal

TensorMath.lua, doc/maths.md, lib/TH/generic/THTensorMath.c, lib/TH/generic/THTensorMath.h, test/test.lua
- Includes lshift, rshift, bitor, bitand, bitxor
- Includes contributions from Conrado Miranda from twitter.
=> Bitwise operations

lib/TH/CMakeLists.txt, lib/TH/THVector.c, lib/TH/generic/THVectorDispatch.c
this is need to enable AVX codepaths
=> reintroduce USE_AVX* for files which dont have -mavx* set

lib/TH/THTensorApply.h, test/test.lua
Fixes https://github.com/pytorch/pytorch/issues/1036
=> Fix TH_TENSOR_APPLYX_D in the case where dim is inner loop

lib/TH/generic/THTensorLapack.c
=> Make rinfo_ argument optional in btrifact

lib/TH/vector/VSX.c
This was previously completed for other architectures.
=> THVector_(add),(mul) -> (adds),(mul) for VSX.

lib/TH/CMakeLists.txt, lib/TH/THGenerateAllTypes.h, lib/TH/THGenerateByteType.h, lib/TH/THGenerateCharType.h, lib/TH/THGenerateDoubleType.h, lib/TH/THGenerateFloatType.h, lib/TH/THGenerateFloatTypes.h, lib/TH/THGenerateHalfType.h, lib/TH/THGenerateIntType.h, lib/TH/THGenerateIntTypes.h, lib/TH/THGenerateLongType.h, lib/TH/THGenerateShortType.h
This allows to use the `generated/` trick from THC and speed up builds of large files.
=> Add THGenerate*Type.h for all types

lib/TH/THMath.h, lib/TH/generic/THTensorMath.c
=> Ensuring float tensors call float versions of math functions

doc/maths.md
Fixing [Issue #1059 ](https://github.com/torch/torch7/issues/1059)
=> Fixing arctan2 documentation
